#  Задача 2

In [3]:
import re
import numpy as np
from scipy import spatial as sp
from scipy import linalg
from math import sin,exp
import matplotlib

In [4]:
def f(x):
    return sin(x/5.0)*exp(x/10.0)+5*exp(-x/2.0)


In [5]:
x = [1,4,10,15]
a = []

In [6]:
for i in range(len(x)):
    new_line = []
    for j in range(len(x)):
        new_line.append(x[i]**j)
    a.append(new_line)


In [7]:
a = np.array(a)
a

array([[   1,    1,    1,    1],
       [   1,    4,   16,   64],
       [   1,   10,  100, 1000],
       [   1,   15,  225, 3375]])

In [8]:
b = np.array([ f(i) for i in x])
b

array([ 3.25221687,  1.74684595,  2.50541641,  0.63522142])

In [9]:
linalg.solve(a,b)

array([ 4.36264154, -1.29552587,  0.19333685, -0.00823565])